##################################
#   ZlomCore Main Config
#   Made by Paramount_Dev
#   FunPay Link: https://funpay.com/uk/users/14397429/
##################################


##### FURNACE PRIVATE CONFIG #####
items:
  DIAMOND: 3
  DIAMOND_BLOCK: 27
  NETHERITE_INGOT: 5
  NETHERITE_BLOCK: 45
burn_multiplier: 30

custom_furnace:
  name: "&6[Приватная Печь]"
  lore:
    - "&7Эта печь защищает территорию"
    - "&7Активируй её алмазом и углём"

admin_bypass: true
protection_from_player_radius: 10


##### COMBAT MANAGER CONFIG #####
pvp_system:
  protection_duration_days: 7
  combat_cooldown_seconds: 10
  logout_jail_days: 3



##### BOOSTY CONNECTOR CONFIG #####
default-limit: 3
boostyL1: 5
boostyL2: 8
boostyL3: 10
boostyL4: 15
deny-message: "&cВы достигли лимита выставления лотов."
admin-changed-message: "&aАдминистратор изменил ваш лимит лотов на: %limit%"



##### PARACLANS CONFIG #####
max-members: 10
create-price: 1000.0


clan:
  level-costs:
    level-2: 1500
    level-3: 3000
    level-4: 6000
    level-5: 10000


roles:
  level1:
    name: "Новичок"
    can-open-settings: false
    can-accept-requests: false
    can-deny-requests: false
    can-declare-war: false
    can-end-war: false
    can-trade-contract: false
    can-trade-end: false
    can-remove-clan: false
    place-private-furnace: false
    break-private-furnace: false
  level2:
    name: "Бывалый"
    can-open-settings: false
    can-accept-requests: true
    can-deny-requests: true
    can-declare-war: false
    can-end-war: false
    can-trade-contract: false
    can-trade-end: false
    can-remove-clan: false
    place-private-furnace: false
    break-private-furnace: false
  level3:
    name: "Командир"
    can-open-settings: true
    can-accept-requests: true
    can-deny-requests: true
    can-declare-war: true
    can-end-war: true
    can-trade-contract: true
    can-trade-end: true
    can-remove-clan: false
    place-private-furnace: false
    break-private-furnace: false


blacklist:
  - admin
  - owner
  - mod
  - helper
  - staff
  - test
  - "Имя клана"
  - "имя клана"



##### SHOP CONFIG #####

shop:
  items:
    DIAMOND:
      buy-price: 100
      sell-price: 80

    NETHERITE_INGOT:
      buy-price: 500
      sell-price: 400


  tax-percent: 10.0  # Процент комиссии с каждой сделки




##### ORDERS CONFIG #####

max-orders-per-player: 5
blacklisted-materials:
  - BEDROCK
  - COMMAND_BLOCK



##### CHATS CONFIG #####

chat:

  formats:
    clan: "&f[&9Clan&f] &r{player}: {message}"
    global: "&f[&cGlobal&f] &r{player}: {message}"
    jail: "&f[&4Jail&f] &r{player}: {message}"
    local: "&f[&aLocal&f] &r{player}: {message}"
    private: "&f[&5Private&f] &r{player}: {message}"


  radius:
    jail: 100
    local: 100

jail:
  xMin: 0
  xMax: 100
  zMin: 0
  zMax: 100




##### COMMANDS CONFIG #####

spawn:
  price: 100.0
  allow-cross-world: false

homes:
  enabled: false # true - включить /sethome
  cost: 50.0
  cross-world: false

rtp:
  enabled: false
  cost: 75.0
  max-radius: 10000

tpa:
  cross-world: false
  default-cost: 30000

warp:
  create-cost: 500000
  cross-world: false
  default-limit: 1




##### OCCUPATION CONFIG #####

occupation:
  enabled: true
  duration: 30 # секунд
  messages:
    start: "&6%player% начал оккупацию региона!"
    cancelled: "&7Оккупация отменена."
    success: "&cРегион перешел к %player%!"
    failure: "&eОккупация не удалась. Защитников было больше."

  delay-days: 3

  siege-delay-hours: 24           # Время ожидания перед открытием меню после начала осады
  outcome-delay-days: 3           # Время до автоматической обработки исхода (используется в OccupationTimedOutcome)
  min-attackers-for-success: 2    # Минимум игроков в регионе, чтобы исход сработал
  require-attackers: true         # Если false — исход будет происходить даже при отсутствии игроков



##### WORLDS CONFIG #####
world:
  size: 1000
  creation-cost: 500.0
  main-world: world





messages:


  # СООБЩЕНИЯ МИРА
  not-enough-money-world: "&cНедостаточно денег (%cost%) для создания мира."
  world-created: "&aМир '%world%' создан и загружен!"
  teleported-to-own: "&aВы телепортированы в ваш личный мир."
  returned-back: "&aВы вернулись обратно."



  # СООБЩЕНИЯ ЭКОНОМИКИ
  balance: "&aВаш баланс: %balance% зломов"
  sent_money: "&aВы отправили %amount% зломов игроку %player%."
  received_money: "&aВы получили %amount% зломов от %player%."
  added_money: "&aВы выдали %amount% зломов игроку %player%."
  taken_money: "&aВы изъяли %amount% зломов у игрока %player%."
  penalty: "&cВы были оштрафованы на %amount% зломов по причине: %reason%"
  ah_blocked: "&cВам запрещено использовать /ah до %time%. Причина: %reason%"
  ah_block_expired: "&aВаш блок на /ah истёк."

  # БАЗОВЫЕ СООБЩЕНИЯ
  clan-created: "&aКлан {clan} создан!"
  already-in-clan: "&cВы уже в клане."
  clan-exists: "&cКлан с таким именем уже существует."
  clan-name-blacklisted: "&cЭто имя клана запрещено."
  clan-not-found: "&cКлан не найден."
  clan-full: "&cКлан заполнен."
  clan-joined-request: "&aЗаявка на вступление отправлена!"
  only-owner-can-remove: "&cТолько владелец клана может удалить его."
  clan-removed: "&eКлан {clan} был удалён."
  unknown-command: "&cНеизвестная команда."

  # ВОЙНА
  only-owner-can-declarewar: "&cТолько владелец клана может объявить войну."
  wardeclare: "§4{clan1} объявил войну клану {clan2}"
  war-already-declared: "&cВы уже воюете с этим кланом."

  # МИР
  only-owner-can-warend: "&cТолько владелец клана может объявить мир."
  endwar: "§a{clan1} объявил мир клану {clan2}"
  clan-not-war-with: "&cВы не воюете с этим кланом."

  # ТОРГОВОЕ СОГЛАШЕНИЕ
  only-owner-can-tradecontract: "&cТолько владелец клана может объявить торговое соглашение."
  tradecontract: "§a{clan1} заключил торговое соглашение с кланом {clan2}"
  clan-not-trade-with: "&cВы уже имеете торговое соглашения с этим кланом."

  # РАЗОРВАТЬ ТОРГОВОЕ СОГЛАШЕНИЕ
  only-owner-can-tradecontractend: "&cТолько владелец клана может разорвать торговое соглашение."
  tradecontractend: "§4{clan1} разорвал торговое соглашение с кланом {clan2}"
  clan-not-trade-withend: "&cВы не имеете торговое соглашения с этим кланом."

  # ДЕНЕЖНЫЕ ОПЕРАЦИИ
  not-enough-money: "§cУ вас недостаточно зломов для создания клана. Требуется §e{price}$§c."
  money-withdrawn: "§aС вашего счета снято §e{price} зломов §aза создание клана."