name: ZlomCore_PDev
version: '1.0'
main: dev.paramountdev.zlomCore_PDev.ZlomCore_PDev
api-version: '1.21'
author: "ParamountDev"
website: https://funpay.com/uk/users/14397429/

depend: [Vault]
loadbefore:
  - HyperAuctions
  - CrazyAuctions
  - Essentials


commands:

  # CONFIG CHANGER
  openconfigsettings:
    description: Открыть настройки конфигурации
    usage: /openconfigsettings <furnace|boosty|clans>
    permission: configeditor.use


  # BOOSTY CONNECTOR
  checkslots:
    description: Проверка количества доступных слотов
    usage: /checkslots

  boostysetlimit:
    description: Установить лимит слотов игроку
    usage: /boostysetlimit <игрок> <слоты>
    permission: boosty.admin

  # FURNACE PRIVATE
  fp:
    description: Команды для приватных печек
    usage: /fp <give | list>

  # GALAXY ECONOMY
  penalty:
    usage: /penalty <ник> <сумма> <причина>
    permission: customeconomy.admin

  ahblock:
    usage: /ahblock <ник> <время в минутах> <причина>
    permission: customeconomy.admin

  money:
    usage: /money [send|add|take] <ник> <сумма>

  # PARA CLANS
  pclans:
    description: Основная команда для управления кланами
    usage: /pclans <create|join|remove> <имя>
    aliases: [ clan, clans ]

  pshop:
    description: Открывает магазин
    aliases: [ shop ]

  avik:
    description: Меню задач Avik
    usage: /avik

  orders:
    description: Меню заказов
    usage: /orders [create <тип_блока> <кол-во> <цена>]



permissions:

  #BOOSTY_CONNECTOR
  boosty.admin:
    default: op

  configeditor.use:
    default: op

  avik.admin:
    description: Получает оповещения о жалобах
    default: op

  orders.create:
    default: true
  orders.use:
    default: true
