name: ZlomCore_PDev
version: '1.0'
main: dev.paramountdev.zlomCore_PDev.ZlomCore_PDev
api-version: '1.21'

author: "ParamountDev"
website_funpay: https://funpay.com/uk/users/14397429/
website_youtube: https://www.youtube.com/@paramount_dev12
telegram: paramount1_dev


depend: [Vault]
loadbefore:
  - HyperAuctions
  - CrazyAuctions
  - Essentials


commands:

  # CONFIG CHANGER
  openconfigsettings:
    description: Открыть настройки конфигурации
    usage: /openconfigsettings <furnace|boosty|clans>
    permission: configeditor.use


  # BOOSTY CONNECTOR
  checkslots:
    description: Проверка количества доступных слотов
    usage: /checkslots

  boostysetlimit:
    description: Установить лимит слотов игроку
    usage: /boostysetlimit <игрок> <слоты>
    permission: boosty.admin

  # FURNACE PRIVATE
  fp:
    description: Команды для приватных печек
    usage: /fp <give | list>

  # GALAXY ECONOMY
  penalty:
    usage: /penalty <ник> <сумма> <причина>
    permission: customeconomy.admin

  ahblock:
    usage: /ahblock <ник> <время в минутах> <причина>
    permission: customeconomy.admin

  money:
    usage: /money [send|add|take] <ник> <сумма>

  # PARA CLANS
  pclans:
    description: Основная команда для управления кланами
    usage: /pclans <create|join|remove> <имя>
    aliases: [ clan, clans ]

  pshop:
    description: Открывает магазин
    aliases: [ shop ]

  avik:
    description: Меню задач Avik
    usage: /avik

  orders:
    description: Меню заказов
    usage: /orders [create <тип_блока> <кол-во> <цена>]

  spawn:
    description: Телепорт на спавн
  setspawn:
    description: Установить точку спавна

  home:
    description: Телепорт домой
  sethome:
    description: Установить точку дома

  rtp:
    description: Телепорт в случайную точку

  warp:
    description: Телепорт к варпу
  setwarp:
    description: Создание варпа

  tpa:
    description: Запрос на телепортацию
  tpaccept:
    description: Принять запрос на телепортацию
  tpdeny:
    description: Отклонить запрос на телепортацию


permissions:

  #BOOSTY_CONNECTOR
  boosty.admin:
    default: op

  configeditor.use:
    default: op

  avik.admin:
    description: Получает оповещения о жалобах
    default: op

  orders.create:
    default: true
  orders.use:
    default: true


  teleportcore.spawn:
    default: true
  teleportcore.setspawn:
    default: op